### ISSUE TITLE
I'll volunteer

### ISSUE THREAD

**Issue by doug-wade** [azer/get-object-path#2]
@azer I'm sorry to hear about your poor experience with npm and kik.  Per [your post](https://medium.com/@azerbike/i-ve-just-liberated-my-modules-9045c06be67c#.ovptnk4p6), I'd like to volunteer to take ownership of this module and get it back on npm and unblock ampersand clients (https://github.com/azer/get-object-path/issues/1).

**Comment by azer** [comment]
@doug-wade added you as collaborator
